services:
  app:
    build: .
    container_name: budget-app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://host.docker.internal:7687
      NEO4J_PASSWORD: password
    networks:
      - budget-network
  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474" #HTTP
      - "7687:7687" #BOLT
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - budget-network
networks:
  budget-network:
    driver: bridge