server:
  port: 8080
spring:
  application:
    name: budget-finance
  neo4j:
    authentication:
      username: neo4j
      password: password
    uri: bolt://host.docker.internal:7687
    #uri: bolt://localhost:7689