server:
  port: 8080
spring:
  application:
    name: budget-finance
  neo4j:
    authentication:
      username: neo4j
      password: password
    uri: bolt://localhost:7689
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
